<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Active' => 'Attiva',
    'Are you sure you want to delete this user?' => 'Siete sicuri di voler eliminare questo utente?',
    'Banned' => 'Bloccato',
    'Bind to IP' => 'Assegna a indirizzo IP',
    'Browser' => 'Browser',
    'Change own password' => 'Cambia la tua password',
    'Change password' => 'cambia password',
    'Changing password' => 'Cambiando la password',
    'Changing password for user: ' => 'cambiando la password per l\'utente: ',
    'Child permissions' => 'Permessi figli',
    'Child roles' => 'Ruoli figli',
    'Code' => 'Codice',
    'Confirmation Token' => 'Token di conferma',
    'Create' => 'Crea',
    'Created' => 'Creato',
    'Creating permission group' => 'Creazione gruppo di permessi',
    'Current password' => 'Password corrente',
    'Data' => 'Data',
    'Delete' => 'Cancella',
    'Description' => 'Descrizione',
    'E-mail' => 'Indirizzo email',
    'E-mail confirmed' => 'E-mail confermata',
    'E-mail with activation link has been sent to <b>{email}</b>. This link will expire in {minutes} min.' => 'E\' stata inviata una email con il link di attivazione a  <b>{email}</b>. Il link scadrà in {minutes} min.',
    'Edit' => 'Modifica',
    'Editing' => 'Modifica',
    'Editing permission group' => 'Modifica gruppo permessi',
    'Editing permission: ' => 'Modifica permesso:',
    'Editing role: ' => 'Modifica ruolo:',
    'Editing user: ' => 'Modifica utente:',
    'For example: 123.34.56.78, 168.111.192.12' => 'Por esempio: 123.34.56.78, 168.111.192.12',
    'Group' => 'Gruppo',
    'ID' => 'Id',
    'Inactive' => 'Inattivo',
    'IP' => 'IP',
    'Language' => 'Lingua',
    'Login' => 'Login',
    'Name' => 'Nome',
    'OS' => 'Sistema Operativo',
    'Password' => 'Password',
    'Password has been changed' => 'La password è stata cambiata',
    'Permission creation' => 'Creazione permesso',
    'Permission groups' => 'Gruppo di permessi',
    'Permissions' => 'Permesso',
    'Permissions for role:' => 'Permesso per il ruolo:',
    'Refresh routes' => 'Aggiorna percorsi',
    'Refresh routes (and delete unused)' => 'Aggiorna permessi (e cancella gli inesistenti)',
    'Registration IP' => 'Registrazione IP',
    'Repeat password' => 'Ripeti password',
    'Reset' => 'Resetta',
    'Role creation' => 'Creazione ruolo',
    'Roles' => 'Ruoli',
    'Roles and permissions' => 'Ruoli e permessi',
    'Roles and permissions for user:' => 'Ruoli e permessi per l\'utente: ',
    'Routes that are not exists in this application will be deleted. Do not recommended for application with "advanced" structure, because frontend and backend have they own set of routes.' => 'I percordi che non esistono saranno cancellati. Non raccomandato per l\'ambiente con struttura avanzata, perchè il frontend ed il backend hanno differenti percorsi',
    'Rule' => 'Regola',
    'Save' => 'Salva',
    'Saved' => 'Salvato',
    'Search' => 'Cerca',
    'Search route' => 'Cerca percorso',
    'Settings for permission' => 'Configurazione permessi',
    'Show all' => 'Mostra tutti',
    'Show only selected' => 'Mostra solo i selezionati',
    'Status' => 'Stato',
    'Superadmin' => 'Super admin',
    'Token' => 'Token',
    'Too many attempts' => 'Troppi tentativi',
    'Type' => 'Tipo',
    'Updated' => 'Aggiornato',
    'User' => 'Utente',
    'User agent' => 'User agent',
    'User creation' => 'Creazione utente',
    'Users' => 'Utenti',
    'Visit Time' => 'Ora di visita',
    'Visit log' => 'Registro attività',
    'Wrong format. Enter valid IPs separated by comma' => 'Formato errato. Inserire un indirizzo IP valido separato da virgola',
    'Wrong password' => 'Password errata',
    'You can not change own permissions' => 'Non puoi cambiare i tuoi permessi',
];
