<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Username' => 'Nome utente',
    'Authorization' => 'Autorizzazione',
    'Captcha' => 'Codice di verifica',
    'Check your E-mail for further instructions' => 'Controlla l\'email per ulteriori istruzioni',
    'Check your e-mail {email} for instructions to activate account' => 'Controlla la tua e-mail {email} per attivare l\'account.',
    'Confirm' => 'Conferma',
    'Confirm E-mail' => 'Conferma l\'email',
    'Continue' => 'Continua',
    'Could not send confirmation email' => 'Non è stato possibile inviare l\email di conferma',
    'E-mail' => 'Indirizzo e-mail',
    'E-mail confirmation for' => 'E-mail di conferma per',
    'E-mail confirmed' => 'Indirizzo email confermato',
    'E-mail is invalid' => 'L\'email non è valida',
    'Forgot password ?' => 'Password dimenticata?',
    'Incorrect username or password.' => 'Nome utente o password non corretti.',
    'Login' => 'Login',
    'Login has been taken' => 'Il login è già utilizzato',
    'Password' => 'Password',
    'Password recovery' => 'Recupero password',
    'Password reset for' => 'Reset password per',
    'Recover' => 'Recupero',
    'Register' => 'Registrati',
    'Registration' => 'Registrazione',
    'Registration - confirm your e-mail' => 'Registrazione - Conferma e-mail',
    'Remember me' => 'Ricordami',
    'Repeat password' => 'Ripeti password',
    'This E-mail already exists' => 'Questo indirizzo email già esisten',
    'Token not found. It may be expired' => 'Token non trovato. Potrebbe essere scaduto',
    'Token not found. It may be expired. Try reset password once more' => 'Token non trovato. Potrebbe essere scaduto. Prova a resettare la password di nuovo.',
    'Too many attempts' => 'Troppi tentativi',
    'Unable to send message for email provided' => 'Impossible inviare il messaggio all\'indirizzo email indicato',
    'You could not login from this IP' => 'Non puoi effettuare il login da questo indirizzo IP',
];
